version: 0.2

env:
  parameter-store:
    DOCKERHUB_USER: "/docker/username"
  secrets-manager:
    DOCKERHUB_TOKEN: "docker_credentials:token"

phases:
  pre_build:
    commands:
      # - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin 
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 891377082819.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      # - docker build -t my-angular-app:latest .
      - docker build -t angular_repo .

  post_build:
    commands:
      # - docker tag my-angular-app:latest ${DOCKERHUB_USER}/my-angular-app:latest
      # - docker push ${DOCKERHUB_USER}/my-angular-app:latest
      - docker tag angular_repo:latest 891377082819.dkr.ecr.ap-south-1.amazonaws.com/angular_repo:latest
      - docker push 891377082819.dkr.ecr.ap-south-1.amazonaws.com/angular_repo:latest
      - printf '[{ "name": "angularapp", "imageUri": "891377082819.dkr.ecr.ap-south-1.amazonaws.com/angular_repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
